(cl:defpackage pal_web_msgs-srv
  (:use )
  (:export
   "GETLASTTOUCHWEB"
   "<GETLASTTOUCHWEB-REQUEST>"
   "GETLASTTOUCHWEB-REQUEST"
   "<GETLASTTOUCHWEB-RESPONSE>"
   "GETLASTTOUCHWEB-RESPONSE"
  ))

