# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hri_actions_msgs/FaceOverlayGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FaceOverlayGoal(genpy.Message):
  _md5sum = "953d334319802dfd447bdb6867044fd8"
  _type = "hri_actions_msgs/FaceOverlayGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======


# URL of the picture/animation to overlay on the face; currently only supports
# absolute local path
string media_url

# duration, in seconds, of the overlay visibility
# - if the duration is larger than the duration of the animation, the animation
# will loop.
# - a duration of 0 means 'forever'. In this case, the action *will never
# complete* on its own. Cancelling the action will remove the overlay from the
# face.
float32 duration


###############################################
## LAYER

# display the image in the background (the eye's iris/pupil will be drawn on
# top of the overlay
uint8 BACKGROUND=0
# display the image on top of the eye (the eye's iris/pupil will be occluded by
# the image, except where transparent)
uint8 FOREGROUND=1

# one of BACKGROUND or FOREGROUND
uint8 layer

###############################################
## LAYOUT

# extend the provided image to cover both eyes.
# Note: this typically is the only sensible option for robot with a single face panel
uint8 EXTEND=0
# on robots with 2 panels (one per eye), copy the provided image onto each eye
uint8 COPY=1
#  on robots with 2 panels (one per eye), mirror the provided image onto each eyes (symmetry over the vertical axis)
uint8 MIRROR=2
# on robots with 2 panels (one per eye), only display the image on the left eye
uint8 LEFT_EYE_ONLY=3
# on robots with 2 panels (one per eye), only display the image on the right eye
uint8 RIGHT_EYE_ONLY=4

# one of the layout constant defined above
uint8 layout


# scale of the image: 1.0 (default) means full width of the face/eye (depending
# on the chosen layout); 0.1 means 10% of the width.
# Note that any value <= 0.0 is ignored (replaced by 1.0)
float32 scale

# position offset, expressed as a proportion of the face or eye's width/height. Values
# in [-1.0, 1.0] range.
#
# (0.0, 0.0) means that the image is centered with the face/eye
# (-1.0, 1.0) means that the image's center would be located in the top left
# corner of the face/eye panel.
float32 offset_x
float32 offset_y

###############################################
## EFFECTS

# if true, the overlay will fade in/fade out
bool fade

"""
  # Pseudo-constants
  BACKGROUND = 0
  FOREGROUND = 1
  EXTEND = 0
  COPY = 1
  MIRROR = 2
  LEFT_EYE_ONLY = 3
  RIGHT_EYE_ONLY = 4

  __slots__ = ['media_url','duration','layer','layout','scale','offset_x','offset_y','fade']
  _slot_types = ['string','float32','uint8','uint8','float32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       media_url,duration,layer,layout,scale,offset_x,offset_y,fade

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FaceOverlayGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.media_url is None:
        self.media_url = ''
      if self.duration is None:
        self.duration = 0.
      if self.layer is None:
        self.layer = 0
      if self.layout is None:
        self.layout = 0
      if self.scale is None:
        self.scale = 0.
      if self.offset_x is None:
        self.offset_x = 0.
      if self.offset_y is None:
        self.offset_y = 0.
      if self.fade is None:
        self.fade = False
    else:
      self.media_url = ''
      self.duration = 0.
      self.layer = 0
      self.layout = 0
      self.scale = 0.
      self.offset_x = 0.
      self.offset_y = 0.
      self.fade = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.media_url
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f2B3fB().pack(_x.duration, _x.layer, _x.layout, _x.scale, _x.offset_x, _x.offset_y, _x.fade))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.media_url = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.media_url = str[start:end]
      _x = self
      start = end
      end += 19
      (_x.duration, _x.layer, _x.layout, _x.scale, _x.offset_x, _x.offset_y, _x.fade,) = _get_struct_f2B3fB().unpack(str[start:end])
      self.fade = bool(self.fade)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.media_url
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f2B3fB().pack(_x.duration, _x.layer, _x.layout, _x.scale, _x.offset_x, _x.offset_y, _x.fade))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.media_url = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.media_url = str[start:end]
      _x = self
      start = end
      end += 19
      (_x.duration, _x.layer, _x.layout, _x.scale, _x.offset_x, _x.offset_y, _x.fade,) = _get_struct_f2B3fB().unpack(str[start:end])
      self.fade = bool(self.fade)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f2B3fB = None
def _get_struct_f2B3fB():
    global _struct_f2B3fB
    if _struct_f2B3fB is None:
        _struct_f2B3fB = struct.Struct("<f2B3fB")
    return _struct_f2B3fB
