// Generated by gencpp from file attention_manager/SetPolicy.msg
// DO NOT EDIT!


#ifndef ATTENTION_MANAGER_MESSAGE_SETPOLICY_H
#define ATTENTION_MANAGER_MESSAGE_SETPOLICY_H

#include <ros/service_traits.h>


#include <attention_manager/SetPolicyRequest.h>
#include <attention_manager/SetPolicyResponse.h>


namespace attention_manager
{

struct SetPolicy
{

typedef SetPolicyRequest Request;
typedef SetPolicyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPolicy
} // namespace attention_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::attention_manager::SetPolicy > {
  static const char* value()
  {
    return "0f86d129016b02b119d57fd98d1af8fc";
  }

  static const char* value(const ::attention_manager::SetPolicy&) { return value(); }
};

template<>
struct DataType< ::attention_manager::SetPolicy > {
  static const char* value()
  {
    return "attention_manager/SetPolicy";
  }

  static const char* value(const ::attention_manager::SetPolicy&) { return value(); }
};


// service_traits::MD5Sum< ::attention_manager::SetPolicyRequest> should match
// service_traits::MD5Sum< ::attention_manager::SetPolicy >
template<>
struct MD5Sum< ::attention_manager::SetPolicyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::attention_manager::SetPolicy >::value();
  }
  static const char* value(const ::attention_manager::SetPolicyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::attention_manager::SetPolicyRequest> should match
// service_traits::DataType< ::attention_manager::SetPolicy >
template<>
struct DataType< ::attention_manager::SetPolicyRequest>
{
  static const char* value()
  {
    return DataType< ::attention_manager::SetPolicy >::value();
  }
  static const char* value(const ::attention_manager::SetPolicyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::attention_manager::SetPolicyResponse> should match
// service_traits::MD5Sum< ::attention_manager::SetPolicy >
template<>
struct MD5Sum< ::attention_manager::SetPolicyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::attention_manager::SetPolicy >::value();
  }
  static const char* value(const ::attention_manager::SetPolicyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::attention_manager::SetPolicyResponse> should match
// service_traits::DataType< ::attention_manager::SetPolicy >
template<>
struct DataType< ::attention_manager::SetPolicyResponse>
{
  static const char* value()
  {
    return DataType< ::attention_manager::SetPolicy >::value();
  }
  static const char* value(const ::attention_manager::SetPolicyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATTENTION_MANAGER_MESSAGE_SETPOLICY_H
