// Generated by gencpp from file gpt_server/GPTGenerateResponse.msg
// DO NOT EDIT!


#ifndef GPT_SERVER_MESSAGE_GPTGENERATERESPONSE_H
#define GPT_SERVER_MESSAGE_GPTGENERATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gpt_server
{
template <class ContainerAllocator>
struct GPTGenerateResponse_
{
  typedef GPTGenerateResponse_<ContainerAllocator> Type;

  GPTGenerateResponse_()
    : response()  {
    }
  GPTGenerateResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::gpt_server::GPTGenerateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gpt_server::GPTGenerateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GPTGenerateResponse_

typedef ::gpt_server::GPTGenerateResponse_<std::allocator<void> > GPTGenerateResponse;

typedef boost::shared_ptr< ::gpt_server::GPTGenerateResponse > GPTGenerateResponsePtr;
typedef boost::shared_ptr< ::gpt_server::GPTGenerateResponse const> GPTGenerateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gpt_server::GPTGenerateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gpt_server::GPTGenerateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gpt_server::GPTGenerateResponse_<ContainerAllocator1> & lhs, const ::gpt_server::GPTGenerateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gpt_server::GPTGenerateResponse_<ContainerAllocator1> & lhs, const ::gpt_server::GPTGenerateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gpt_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gpt_server::GPTGenerateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpt_server::GPTGenerateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gpt_server::GPTGenerateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gpt_server::GPTGenerateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpt_server::GPTGenerateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpt_server::GPTGenerateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gpt_server::GPTGenerateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::gpt_server::GPTGenerateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::gpt_server::GPTGenerateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gpt_server/GPTGenerateResponse";
  }

  static const char* value(const ::gpt_server::GPTGenerateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gpt_server::GPTGenerateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
"\n"
;
  }

  static const char* value(const ::gpt_server::GPTGenerateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gpt_server::GPTGenerateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPTGenerateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gpt_server::GPTGenerateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gpt_server::GPTGenerateResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPT_SERVER_MESSAGE_GPTGENERATERESPONSE_H
