; Auto-generated. Do not edit!


(cl:in-package hri_actions_msgs-msg)


;//! \htmlinclude ApplicationControlFeedback.msg.html

(cl:defclass <ApplicationControlFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ApplicationControlFeedback (<ApplicationControlFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ApplicationControlFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ApplicationControlFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hri_actions_msgs-msg:<ApplicationControlFeedback> is deprecated: use hri_actions_msgs-msg:ApplicationControlFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ApplicationControlFeedback>) ostream)
  "Serializes a message object of type '<ApplicationControlFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ApplicationControlFeedback>) istream)
  "Deserializes a message object of type '<ApplicationControlFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ApplicationControlFeedback>)))
  "Returns string type for a message object of type '<ApplicationControlFeedback>"
  "hri_actions_msgs/ApplicationControlFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ApplicationControlFeedback)))
  "Returns string type for a message object of type 'ApplicationControlFeedback"
  "hri_actions_msgs/ApplicationControlFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ApplicationControlFeedback>)))
  "Returns md5sum for a message object of type '<ApplicationControlFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ApplicationControlFeedback)))
  "Returns md5sum for a message object of type 'ApplicationControlFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ApplicationControlFeedback>)))
  "Returns full string definition for message of type '<ApplicationControlFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ApplicationControlFeedback)))
  "Returns full string definition for message of type 'ApplicationControlFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ApplicationControlFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ApplicationControlFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ApplicationControlFeedback
))
