; Auto-generated. Do not edit!


(cl:in-package hri_actions_msgs-msg)


;//! \htmlinclude ApplicationControlResult.msg.html

(cl:defclass <ApplicationControlResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ApplicationControlResult (<ApplicationControlResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ApplicationControlResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ApplicationControlResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hri_actions_msgs-msg:<ApplicationControlResult> is deprecated: use hri_actions_msgs-msg:ApplicationControlResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ApplicationControlResult>) ostream)
  "Serializes a message object of type '<ApplicationControlResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ApplicationControlResult>) istream)
  "Deserializes a message object of type '<ApplicationControlResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ApplicationControlResult>)))
  "Returns string type for a message object of type '<ApplicationControlResult>"
  "hri_actions_msgs/ApplicationControlResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ApplicationControlResult)))
  "Returns string type for a message object of type 'ApplicationControlResult"
  "hri_actions_msgs/ApplicationControlResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ApplicationControlResult>)))
  "Returns md5sum for a message object of type '<ApplicationControlResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ApplicationControlResult)))
  "Returns md5sum for a message object of type 'ApplicationControlResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ApplicationControlResult>)))
  "Returns full string definition for message of type '<ApplicationControlResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ApplicationControlResult)))
  "Returns full string definition for message of type 'ApplicationControlResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ApplicationControlResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ApplicationControlResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ApplicationControlResult
))
