; Auto-generated. Do not edit!


(cl:in-package hri_actions_msgs-msg)


;//! \htmlinclude ApplicationControlGoal.msg.html

(cl:defclass <ApplicationControlGoal> (roslisp-msg-protocol:ros-message)
  ((parameters
    :reader parameters
    :initarg :parameters
    :type cl:string
    :initform ""))
)

(cl:defclass ApplicationControlGoal (<ApplicationControlGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ApplicationControlGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ApplicationControlGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hri_actions_msgs-msg:<ApplicationControlGoal> is deprecated: use hri_actions_msgs-msg:ApplicationControlGoal instead.")))

(cl:ensure-generic-function 'parameters-val :lambda-list '(m))
(cl:defmethod parameters-val ((m <ApplicationControlGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hri_actions_msgs-msg:parameters-val is deprecated.  Use hri_actions_msgs-msg:parameters instead.")
  (parameters m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ApplicationControlGoal>) ostream)
  "Serializes a message object of type '<ApplicationControlGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'parameters))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'parameters))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ApplicationControlGoal>) istream)
  "Deserializes a message object of type '<ApplicationControlGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'parameters) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'parameters) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ApplicationControlGoal>)))
  "Returns string type for a message object of type '<ApplicationControlGoal>"
  "hri_actions_msgs/ApplicationControlGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ApplicationControlGoal)))
  "Returns string type for a message object of type 'ApplicationControlGoal"
  "hri_actions_msgs/ApplicationControlGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ApplicationControlGoal>)))
  "Returns md5sum for a message object of type '<ApplicationControlGoal>"
  "b96cd7929ab82d8413ba620379c440ce")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ApplicationControlGoal)))
  "Returns md5sum for a message object of type 'ApplicationControlGoal"
  "b96cd7929ab82d8413ba620379c440ce")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ApplicationControlGoal>)))
  "Returns full string definition for message of type '<ApplicationControlGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# an (optional) JSON-encoded string passed to the underlying application~%# controller.~%string parameters~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ApplicationControlGoal)))
  "Returns full string definition for message of type 'ApplicationControlGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# an (optional) JSON-encoded string passed to the underlying application~%# controller.~%string parameters~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ApplicationControlGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'parameters))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ApplicationControlGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ApplicationControlGoal
    (cl:cons ':parameters (parameters msg))
))
