; Auto-generated. Do not edit!


(cl:in-package hri_actions_msgs-msg)


;//! \htmlinclude FaceOverlayResult.msg.html

(cl:defclass <FaceOverlayResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass FaceOverlayResult (<FaceOverlayResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FaceOverlayResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FaceOverlayResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hri_actions_msgs-msg:<FaceOverlayResult> is deprecated: use hri_actions_msgs-msg:FaceOverlayResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FaceOverlayResult>) ostream)
  "Serializes a message object of type '<FaceOverlayResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FaceOverlayResult>) istream)
  "Deserializes a message object of type '<FaceOverlayResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FaceOverlayResult>)))
  "Returns string type for a message object of type '<FaceOverlayResult>"
  "hri_actions_msgs/FaceOverlayResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FaceOverlayResult)))
  "Returns string type for a message object of type 'FaceOverlayResult"
  "hri_actions_msgs/FaceOverlayResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FaceOverlayResult>)))
  "Returns md5sum for a message object of type '<FaceOverlayResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FaceOverlayResult)))
  "Returns md5sum for a message object of type 'FaceOverlayResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FaceOverlayResult>)))
  "Returns full string definition for message of type '<FaceOverlayResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FaceOverlayResult)))
  "Returns full string definition for message of type 'FaceOverlayResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FaceOverlayResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FaceOverlayResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FaceOverlayResult
))
