; Auto-generated. Do not edit!


(cl:in-package hri_actions_msgs-msg)


;//! \htmlinclude LookAtGoal.msg.html

(cl:defclass <LookAtGoal> (roslisp-msg-protocol:ros-message)
  ((look_goal
    :reader look_goal
    :initarg :look_goal
    :type geometry_msgs-msg:PointStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PointStamped)))
)

(cl:defclass LookAtGoal (<LookAtGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LookAtGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LookAtGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hri_actions_msgs-msg:<LookAtGoal> is deprecated: use hri_actions_msgs-msg:LookAtGoal instead.")))

(cl:ensure-generic-function 'look_goal-val :lambda-list '(m))
(cl:defmethod look_goal-val ((m <LookAtGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hri_actions_msgs-msg:look_goal-val is deprecated.  Use hri_actions_msgs-msg:look_goal instead.")
  (look_goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LookAtGoal>) ostream)
  "Serializes a message object of type '<LookAtGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'look_goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LookAtGoal>) istream)
  "Deserializes a message object of type '<LookAtGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'look_goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LookAtGoal>)))
  "Returns string type for a message object of type '<LookAtGoal>"
  "hri_actions_msgs/LookAtGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LookAtGoal)))
  "Returns string type for a message object of type 'LookAtGoal"
  "hri_actions_msgs/LookAtGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LookAtGoal>)))
  "Returns md5sum for a message object of type '<LookAtGoal>"
  "fe8d75ae2fc43987e4a29bd6b4c45be4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LookAtGoal)))
  "Returns md5sum for a message object of type 'LookAtGoal"
  "fe8d75ae2fc43987e4a29bd6b4c45be4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LookAtGoal>)))
  "Returns full string definition for message of type '<LookAtGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PointStamped look_goal~%~%================================================================================~%MSG: geometry_msgs/PointStamped~%# This represents a Point with reference coordinate frame and timestamp~%Header header~%Point point~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LookAtGoal)))
  "Returns full string definition for message of type 'LookAtGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PointStamped look_goal~%~%================================================================================~%MSG: geometry_msgs/PointStamped~%# This represents a Point with reference coordinate frame and timestamp~%Header header~%Point point~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LookAtGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'look_goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LookAtGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LookAtGoal
    (cl:cons ':look_goal (look_goal msg))
))
