; Auto-generated. Do not edit!


(cl:in-package hri_actions_msgs-msg)


;//! \htmlinclude LookAtResult.msg.html

(cl:defclass <LookAtResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass LookAtResult (<LookAtResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LookAtResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LookAtResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hri_actions_msgs-msg:<LookAtResult> is deprecated: use hri_actions_msgs-msg:LookAtResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LookAtResult>) ostream)
  "Serializes a message object of type '<LookAtResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LookAtResult>) istream)
  "Deserializes a message object of type '<LookAtResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LookAtResult>)))
  "Returns string type for a message object of type '<LookAtResult>"
  "hri_actions_msgs/LookAtResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LookAtResult)))
  "Returns string type for a message object of type 'LookAtResult"
  "hri_actions_msgs/LookAtResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LookAtResult>)))
  "Returns md5sum for a message object of type '<LookAtResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LookAtResult)))
  "Returns md5sum for a message object of type 'LookAtResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LookAtResult>)))
  "Returns full string definition for message of type '<LookAtResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LookAtResult)))
  "Returns full string definition for message of type 'LookAtResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LookAtResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LookAtResult>))
  "Converts a ROS message object to a list"
  (cl:list 'LookAtResult
))
