; Auto-generated. Do not edit!


(cl:in-package hri_actions_msgs-msg)


;//! \htmlinclude PointTrajectoryFeedback.msg.html

(cl:defclass <PointTrajectoryFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PointTrajectoryFeedback (<PointTrajectoryFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PointTrajectoryFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PointTrajectoryFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hri_actions_msgs-msg:<PointTrajectoryFeedback> is deprecated: use hri_actions_msgs-msg:PointTrajectoryFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PointTrajectoryFeedback>) ostream)
  "Serializes a message object of type '<PointTrajectoryFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PointTrajectoryFeedback>) istream)
  "Deserializes a message object of type '<PointTrajectoryFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PointTrajectoryFeedback>)))
  "Returns string type for a message object of type '<PointTrajectoryFeedback>"
  "hri_actions_msgs/PointTrajectoryFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PointTrajectoryFeedback)))
  "Returns string type for a message object of type 'PointTrajectoryFeedback"
  "hri_actions_msgs/PointTrajectoryFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PointTrajectoryFeedback>)))
  "Returns md5sum for a message object of type '<PointTrajectoryFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PointTrajectoryFeedback)))
  "Returns md5sum for a message object of type 'PointTrajectoryFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PointTrajectoryFeedback>)))
  "Returns full string definition for message of type '<PointTrajectoryFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PointTrajectoryFeedback)))
  "Returns full string definition for message of type 'PointTrajectoryFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PointTrajectoryFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PointTrajectoryFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PointTrajectoryFeedback
))
