; Auto-generated. Do not edit!


(cl:in-package hri_actions_msgs-msg)


;//! \htmlinclude PointTrajectoryResult.msg.html

(cl:defclass <PointTrajectoryResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PointTrajectoryResult (<PointTrajectoryResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PointTrajectoryResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PointTrajectoryResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hri_actions_msgs-msg:<PointTrajectoryResult> is deprecated: use hri_actions_msgs-msg:PointTrajectoryResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PointTrajectoryResult>) ostream)
  "Serializes a message object of type '<PointTrajectoryResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PointTrajectoryResult>) istream)
  "Deserializes a message object of type '<PointTrajectoryResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PointTrajectoryResult>)))
  "Returns string type for a message object of type '<PointTrajectoryResult>"
  "hri_actions_msgs/PointTrajectoryResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PointTrajectoryResult)))
  "Returns string type for a message object of type 'PointTrajectoryResult"
  "hri_actions_msgs/PointTrajectoryResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PointTrajectoryResult>)))
  "Returns md5sum for a message object of type '<PointTrajectoryResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PointTrajectoryResult)))
  "Returns md5sum for a message object of type 'PointTrajectoryResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PointTrajectoryResult>)))
  "Returns full string definition for message of type '<PointTrajectoryResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PointTrajectoryResult)))
  "Returns full string definition for message of type 'PointTrajectoryResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PointTrajectoryResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PointTrajectoryResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PointTrajectoryResult
))
