// Generated by gencpp from file hri_actions_msgs/ApplicationControlActionGoal.msg
// DO NOT EDIT!


#ifndef HRI_ACTIONS_MSGS_MESSAGE_APPLICATIONCONTROLACTIONGOAL_H
#define HRI_ACTIONS_MSGS_MESSAGE_APPLICATIONCONTROLACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <hri_actions_msgs/ApplicationControlGoal.h>

namespace hri_actions_msgs
{
template <class ContainerAllocator>
struct ApplicationControlActionGoal_
{
  typedef ApplicationControlActionGoal_<ContainerAllocator> Type;

  ApplicationControlActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  ApplicationControlActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::hri_actions_msgs::ApplicationControlGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ApplicationControlActionGoal_

typedef ::hri_actions_msgs::ApplicationControlActionGoal_<std::allocator<void> > ApplicationControlActionGoal;

typedef boost::shared_ptr< ::hri_actions_msgs::ApplicationControlActionGoal > ApplicationControlActionGoalPtr;
typedef boost::shared_ptr< ::hri_actions_msgs::ApplicationControlActionGoal const> ApplicationControlActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator1> & lhs, const ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator1> & lhs, const ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hri_actions_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fa64d94c7b412dad4800dc20b792da5";
  }

  static const char* value(const ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fa64d94c7b412daULL;
  static const uint64_t static_value2 = 0xd4800dc20b792da5ULL;
};

template<class ContainerAllocator>
struct DataType< ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hri_actions_msgs/ApplicationControlActionGoal";
  }

  static const char* value(const ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ApplicationControlGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: hri_actions_msgs/ApplicationControlGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# an (optional) JSON-encoded string passed to the underlying application\n"
"# controller.\n"
"string parameters\n"
;
  }

  static const char* value(const ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ApplicationControlActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hri_actions_msgs::ApplicationControlActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::hri_actions_msgs::ApplicationControlGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRI_ACTIONS_MSGS_MESSAGE_APPLICATIONCONTROLACTIONGOAL_H
