// Generated by gencpp from file hri_actions_msgs/FaceOverlayAction.msg
// DO NOT EDIT!


#ifndef HRI_ACTIONS_MSGS_MESSAGE_FACEOVERLAYACTION_H
#define HRI_ACTIONS_MSGS_MESSAGE_FACEOVERLAYACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hri_actions_msgs/FaceOverlayActionGoal.h>
#include <hri_actions_msgs/FaceOverlayActionResult.h>
#include <hri_actions_msgs/FaceOverlayActionFeedback.h>

namespace hri_actions_msgs
{
template <class ContainerAllocator>
struct FaceOverlayAction_
{
  typedef FaceOverlayAction_<ContainerAllocator> Type;

  FaceOverlayAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  FaceOverlayAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::hri_actions_msgs::FaceOverlayActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::hri_actions_msgs::FaceOverlayActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::hri_actions_msgs::FaceOverlayActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator> const> ConstPtr;

}; // struct FaceOverlayAction_

typedef ::hri_actions_msgs::FaceOverlayAction_<std::allocator<void> > FaceOverlayAction;

typedef boost::shared_ptr< ::hri_actions_msgs::FaceOverlayAction > FaceOverlayActionPtr;
typedef boost::shared_ptr< ::hri_actions_msgs::FaceOverlayAction const> FaceOverlayActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator1> & lhs, const ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator1> & lhs, const ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hri_actions_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f61684e206363bfd1066b6cbc9de109";
  }

  static const char* value(const ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f61684e206363bfULL;
  static const uint64_t static_value2 = 0xd1066b6cbc9de109ULL;
};

template<class ContainerAllocator>
struct DataType< ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hri_actions_msgs/FaceOverlayAction";
  }

  static const char* value(const ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"FaceOverlayActionGoal action_goal\n"
"FaceOverlayActionResult action_result\n"
"FaceOverlayActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: hri_actions_msgs/FaceOverlayActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"FaceOverlayGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: hri_actions_msgs/FaceOverlayGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"\n"
"# URL of the picture/animation to overlay on the face; currently only supports\n"
"# absolute local path\n"
"string media_url\n"
"\n"
"# duration, in seconds, of the overlay visibility\n"
"# - if the duration is larger than the duration of the animation, the animation\n"
"# will loop.\n"
"# - a duration of 0 means 'forever'. In this case, the action *will never\n"
"# complete* on its own. Cancelling the action will remove the overlay from the\n"
"# face.\n"
"float32 duration\n"
"\n"
"\n"
"###############################################\n"
"## LAYER\n"
"\n"
"# display the image in the background (the eye's iris/pupil will be drawn on\n"
"# top of the overlay\n"
"uint8 BACKGROUND=0\n"
"# display the image on top of the eye (the eye's iris/pupil will be occluded by\n"
"# the image, except where transparent)\n"
"uint8 FOREGROUND=1\n"
"\n"
"# one of BACKGROUND or FOREGROUND\n"
"uint8 layer\n"
"\n"
"###############################################\n"
"## LAYOUT\n"
"\n"
"# extend the provided image to cover both eyes.\n"
"# Note: this typically is the only sensible option for robot with a single face panel\n"
"uint8 EXTEND=0\n"
"# on robots with 2 panels (one per eye), copy the provided image onto each eye\n"
"uint8 COPY=1\n"
"#  on robots with 2 panels (one per eye), mirror the provided image onto each eyes (symmetry over the vertical axis)\n"
"uint8 MIRROR=2\n"
"# on robots with 2 panels (one per eye), only display the image on the left eye\n"
"uint8 LEFT_EYE_ONLY=3\n"
"# on robots with 2 panels (one per eye), only display the image on the right eye\n"
"uint8 RIGHT_EYE_ONLY=4\n"
"\n"
"# one of the layout constant defined above\n"
"uint8 layout\n"
"\n"
"\n"
"# scale of the image: 1.0 (default) means full width of the face/eye (depending\n"
"# on the chosen layout); 0.1 means 10% of the width.\n"
"# Note that any value <= 0.0 is ignored (replaced by 1.0)\n"
"float32 scale\n"
"\n"
"# position offset, expressed as a proportion of the face or eye's width/height. Values\n"
"# in [-1.0, 1.0] range.\n"
"#\n"
"# (0.0, 0.0) means that the image is centered with the face/eye\n"
"# (-1.0, 1.0) means that the image's center would be located in the top left\n"
"# corner of the face/eye panel.\n"
"float32 offset_x\n"
"float32 offset_y\n"
"\n"
"###############################################\n"
"## EFFECTS\n"
"\n"
"# if true, the overlay will fade in/fade out\n"
"bool fade\n"
"\n"
"\n"
"================================================================================\n"
"MSG: hri_actions_msgs/FaceOverlayActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"FaceOverlayResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: hri_actions_msgs/FaceOverlayResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"================================================================================\n"
"MSG: hri_actions_msgs/FaceOverlayActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"FaceOverlayFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: hri_actions_msgs/FaceOverlayFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"\n"
;
  }

  static const char* value(const ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceOverlayAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hri_actions_msgs::FaceOverlayAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::hri_actions_msgs::FaceOverlayActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::hri_actions_msgs::FaceOverlayActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::hri_actions_msgs::FaceOverlayActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRI_ACTIONS_MSGS_MESSAGE_FACEOVERLAYACTION_H
