// Generated by gencpp from file hri_actions_msgs/LookAtGoal.msg
// DO NOT EDIT!


#ifndef HRI_ACTIONS_MSGS_MESSAGE_LOOKATGOAL_H
#define HRI_ACTIONS_MSGS_MESSAGE_LOOKATGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PointStamped.h>

namespace hri_actions_msgs
{
template <class ContainerAllocator>
struct LookAtGoal_
{
  typedef LookAtGoal_<ContainerAllocator> Type;

  LookAtGoal_()
    : look_goal()  {
    }
  LookAtGoal_(const ContainerAllocator& _alloc)
    : look_goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PointStamped_<ContainerAllocator>  _look_goal_type;
  _look_goal_type look_goal;





  typedef boost::shared_ptr< ::hri_actions_msgs::LookAtGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hri_actions_msgs::LookAtGoal_<ContainerAllocator> const> ConstPtr;

}; // struct LookAtGoal_

typedef ::hri_actions_msgs::LookAtGoal_<std::allocator<void> > LookAtGoal;

typedef boost::shared_ptr< ::hri_actions_msgs::LookAtGoal > LookAtGoalPtr;
typedef boost::shared_ptr< ::hri_actions_msgs::LookAtGoal const> LookAtGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hri_actions_msgs::LookAtGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hri_actions_msgs::LookAtGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hri_actions_msgs::LookAtGoal_<ContainerAllocator1> & lhs, const ::hri_actions_msgs::LookAtGoal_<ContainerAllocator2> & rhs)
{
  return lhs.look_goal == rhs.look_goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hri_actions_msgs::LookAtGoal_<ContainerAllocator1> & lhs, const ::hri_actions_msgs::LookAtGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hri_actions_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hri_actions_msgs::LookAtGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hri_actions_msgs::LookAtGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hri_actions_msgs::LookAtGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hri_actions_msgs::LookAtGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_actions_msgs::LookAtGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_actions_msgs::LookAtGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hri_actions_msgs::LookAtGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe8d75ae2fc43987e4a29bd6b4c45be4";
  }

  static const char* value(const ::hri_actions_msgs::LookAtGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe8d75ae2fc43987ULL;
  static const uint64_t static_value2 = 0xe4a29bd6b4c45be4ULL;
};

template<class ContainerAllocator>
struct DataType< ::hri_actions_msgs::LookAtGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hri_actions_msgs/LookAtGoal";
  }

  static const char* value(const ::hri_actions_msgs::LookAtGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hri_actions_msgs::LookAtGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"geometry_msgs/PointStamped look_goal\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PointStamped\n"
"# This represents a Point with reference coordinate frame and timestamp\n"
"Header header\n"
"Point point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::hri_actions_msgs::LookAtGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hri_actions_msgs::LookAtGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.look_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LookAtGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hri_actions_msgs::LookAtGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hri_actions_msgs::LookAtGoal_<ContainerAllocator>& v)
  {
    s << indent << "look_goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.look_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRI_ACTIONS_MSGS_MESSAGE_LOOKATGOAL_H
