// Generated by gencpp from file hri_actions_msgs/PointTrajectoryGoal.msg
// DO NOT EDIT!


#ifndef HRI_ACTIONS_MSGS_MESSAGE_POINTTRAJECTORYGOAL_H
#define HRI_ACTIONS_MSGS_MESSAGE_POINTTRAJECTORYGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace hri_actions_msgs
{
template <class ContainerAllocator>
struct PointTrajectoryGoal_
{
  typedef PointTrajectoryGoal_<ContainerAllocator> Type;

  PointTrajectoryGoal_()
    : header()
    , targets()
    , times_from_start()  {
    }
  PointTrajectoryGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , targets(_alloc)
    , times_from_start(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _targets_type;
  _targets_type targets;

   typedef std::vector<ros::Duration, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<ros::Duration>> _times_from_start_type;
  _times_from_start_type times_from_start;





  typedef boost::shared_ptr< ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PointTrajectoryGoal_

typedef ::hri_actions_msgs::PointTrajectoryGoal_<std::allocator<void> > PointTrajectoryGoal;

typedef boost::shared_ptr< ::hri_actions_msgs::PointTrajectoryGoal > PointTrajectoryGoalPtr;
typedef boost::shared_ptr< ::hri_actions_msgs::PointTrajectoryGoal const> PointTrajectoryGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator1> & lhs, const ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.targets == rhs.targets &&
    lhs.times_from_start == rhs.times_from_start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator1> & lhs, const ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hri_actions_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d607cbc90aa8b6b7183b03defd85e14";
  }

  static const char* value(const ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d607cbc90aa8b6bULL;
  static const uint64_t static_value2 = 0x7183b03defd85e14ULL;
};

template<class ContainerAllocator>
struct DataType< ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hri_actions_msgs/PointTrajectoryGoal";
  }

  static const char* value(const ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# the header's frame applies to ALL points in the trajectory\n"
"std_msgs/Header header\n"
"geometry_msgs/Point[] targets\n"
"duration[] times_from_start\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.targets);
      stream.next(m.times_from_start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointTrajectoryGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hri_actions_msgs::PointTrajectoryGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "targets[]" << std::endl;
    for (size_t i = 0; i < v.targets.size(); ++i)
    {
      s << indent << "  targets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.targets[i]);
    }
    s << indent << "times_from_start[]" << std::endl;
    for (size_t i = 0; i < v.times_from_start.size(); ++i)
    {
      s << indent << "  times_from_start[" << i << "]: ";
      Printer<ros::Duration>::stream(s, indent + "  ", v.times_from_start[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRI_ACTIONS_MSGS_MESSAGE_POINTTRAJECTORYGOAL_H
