// Generated by gencpp from file attention_manager_msgs/SetPolicy.msg
// DO NOT EDIT!


#ifndef ATTENTION_MANAGER_MSGS_MESSAGE_SETPOLICY_H
#define ATTENTION_MANAGER_MSGS_MESSAGE_SETPOLICY_H

#include <ros/service_traits.h>


#include <attention_manager_msgs/SetPolicyRequest.h>
#include <attention_manager_msgs/SetPolicyResponse.h>


namespace attention_manager_msgs
{

struct SetPolicy
{

typedef SetPolicyRequest Request;
typedef SetPolicyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPolicy
} // namespace attention_manager_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::attention_manager_msgs::SetPolicy > {
  static const char* value()
  {
    return "0f86d129016b02b119d57fd98d1af8fc";
  }

  static const char* value(const ::attention_manager_msgs::SetPolicy&) { return value(); }
};

template<>
struct DataType< ::attention_manager_msgs::SetPolicy > {
  static const char* value()
  {
    return "attention_manager_msgs/SetPolicy";
  }

  static const char* value(const ::attention_manager_msgs::SetPolicy&) { return value(); }
};


// service_traits::MD5Sum< ::attention_manager_msgs::SetPolicyRequest> should match
// service_traits::MD5Sum< ::attention_manager_msgs::SetPolicy >
template<>
struct MD5Sum< ::attention_manager_msgs::SetPolicyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::attention_manager_msgs::SetPolicy >::value();
  }
  static const char* value(const ::attention_manager_msgs::SetPolicyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::attention_manager_msgs::SetPolicyRequest> should match
// service_traits::DataType< ::attention_manager_msgs::SetPolicy >
template<>
struct DataType< ::attention_manager_msgs::SetPolicyRequest>
{
  static const char* value()
  {
    return DataType< ::attention_manager_msgs::SetPolicy >::value();
  }
  static const char* value(const ::attention_manager_msgs::SetPolicyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::attention_manager_msgs::SetPolicyResponse> should match
// service_traits::MD5Sum< ::attention_manager_msgs::SetPolicy >
template<>
struct MD5Sum< ::attention_manager_msgs::SetPolicyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::attention_manager_msgs::SetPolicy >::value();
  }
  static const char* value(const ::attention_manager_msgs::SetPolicyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::attention_manager_msgs::SetPolicyResponse> should match
// service_traits::DataType< ::attention_manager_msgs::SetPolicy >
template<>
struct DataType< ::attention_manager_msgs::SetPolicyResponse>
{
  static const char* value()
  {
    return DataType< ::attention_manager_msgs::SetPolicy >::value();
  }
  static const char* value(const ::attention_manager_msgs::SetPolicyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATTENTION_MANAGER_MSGS_MESSAGE_SETPOLICY_H
