// Generated by gencpp from file emotion_server/EmotionGenerateRequest.msg
// DO NOT EDIT!


#ifndef EMOTION_SERVER_MESSAGE_EMOTIONGENERATEREQUEST_H
#define EMOTION_SERVER_MESSAGE_EMOTIONGENERATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace emotion_server
{
template <class ContainerAllocator>
struct EmotionGenerateRequest_
{
  typedef EmotionGenerateRequest_<ContainerAllocator> Type;

  EmotionGenerateRequest_()
    : wavPath()
    , videoPath()
    , textPath()  {
    }
  EmotionGenerateRequest_(const ContainerAllocator& _alloc)
    : wavPath(_alloc)
    , videoPath(_alloc)
    , textPath(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _wavPath_type;
  _wavPath_type wavPath;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _videoPath_type;
  _videoPath_type videoPath;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _textPath_type;
  _textPath_type textPath;





  typedef boost::shared_ptr< ::emotion_server::EmotionGenerateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::emotion_server::EmotionGenerateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EmotionGenerateRequest_

typedef ::emotion_server::EmotionGenerateRequest_<std::allocator<void> > EmotionGenerateRequest;

typedef boost::shared_ptr< ::emotion_server::EmotionGenerateRequest > EmotionGenerateRequestPtr;
typedef boost::shared_ptr< ::emotion_server::EmotionGenerateRequest const> EmotionGenerateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::emotion_server::EmotionGenerateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::emotion_server::EmotionGenerateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::emotion_server::EmotionGenerateRequest_<ContainerAllocator1> & lhs, const ::emotion_server::EmotionGenerateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.wavPath == rhs.wavPath &&
    lhs.videoPath == rhs.videoPath &&
    lhs.textPath == rhs.textPath;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::emotion_server::EmotionGenerateRequest_<ContainerAllocator1> & lhs, const ::emotion_server::EmotionGenerateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace emotion_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::emotion_server::EmotionGenerateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::emotion_server::EmotionGenerateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::emotion_server::EmotionGenerateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::emotion_server::EmotionGenerateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::emotion_server::EmotionGenerateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::emotion_server::EmotionGenerateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::emotion_server::EmotionGenerateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c7dddfe480c8003a68d59197820d5f0";
  }

  static const char* value(const ::emotion_server::EmotionGenerateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c7dddfe480c8003ULL;
  static const uint64_t static_value2 = 0xa68d59197820d5f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::emotion_server::EmotionGenerateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "emotion_server/EmotionGenerateRequest";
  }

  static const char* value(const ::emotion_server::EmotionGenerateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::emotion_server::EmotionGenerateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string wavPath\n"
"string videoPath\n"
"string textPath\n"
;
  }

  static const char* value(const ::emotion_server::EmotionGenerateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::emotion_server::EmotionGenerateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wavPath);
      stream.next(m.videoPath);
      stream.next(m.textPath);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmotionGenerateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::emotion_server::EmotionGenerateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::emotion_server::EmotionGenerateRequest_<ContainerAllocator>& v)
  {
    s << indent << "wavPath: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.wavPath);
    s << indent << "videoPath: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.videoPath);
    s << indent << "textPath: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.textPath);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EMOTION_SERVER_MESSAGE_EMOTIONGENERATEREQUEST_H
