// Generated by gencpp from file emotion_server/EmotionGenerateResponse.msg
// DO NOT EDIT!


#ifndef EMOTION_SERVER_MESSAGE_EMOTIONGENERATERESPONSE_H
#define EMOTION_SERVER_MESSAGE_EMOTIONGENERATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace emotion_server
{
template <class ContainerAllocator>
struct EmotionGenerateResponse_
{
  typedef EmotionGenerateResponse_<ContainerAllocator> Type;

  EmotionGenerateResponse_()
    : response()  {
    }
  EmotionGenerateResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::emotion_server::EmotionGenerateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::emotion_server::EmotionGenerateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EmotionGenerateResponse_

typedef ::emotion_server::EmotionGenerateResponse_<std::allocator<void> > EmotionGenerateResponse;

typedef boost::shared_ptr< ::emotion_server::EmotionGenerateResponse > EmotionGenerateResponsePtr;
typedef boost::shared_ptr< ::emotion_server::EmotionGenerateResponse const> EmotionGenerateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::emotion_server::EmotionGenerateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::emotion_server::EmotionGenerateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::emotion_server::EmotionGenerateResponse_<ContainerAllocator1> & lhs, const ::emotion_server::EmotionGenerateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::emotion_server::EmotionGenerateResponse_<ContainerAllocator1> & lhs, const ::emotion_server::EmotionGenerateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace emotion_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::emotion_server::EmotionGenerateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::emotion_server::EmotionGenerateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::emotion_server::EmotionGenerateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::emotion_server::EmotionGenerateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::emotion_server::EmotionGenerateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::emotion_server::EmotionGenerateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::emotion_server::EmotionGenerateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::emotion_server::EmotionGenerateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::emotion_server::EmotionGenerateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "emotion_server/EmotionGenerateResponse";
  }

  static const char* value(const ::emotion_server::EmotionGenerateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::emotion_server::EmotionGenerateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
"\n"
;
  }

  static const char* value(const ::emotion_server::EmotionGenerateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::emotion_server::EmotionGenerateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmotionGenerateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::emotion_server::EmotionGenerateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::emotion_server::EmotionGenerateResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EMOTION_SERVER_MESSAGE_EMOTIONGENERATERESPONSE_H
