// Generated by gencpp from file emotion_server/EmotionGenerate.msg
// DO NOT EDIT!


#ifndef EMOTION_SERVER_MESSAGE_EMOTIONGENERATE_H
#define EMOTION_SERVER_MESSAGE_EMOTIONGENERATE_H

#include <ros/service_traits.h>


#include <emotion_server/EmotionGenerateRequest.h>
#include <emotion_server/EmotionGenerateResponse.h>


namespace emotion_server
{

struct EmotionGenerate
{

typedef EmotionGenerateRequest Request;
typedef EmotionGenerateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EmotionGenerate
} // namespace emotion_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::emotion_server::EmotionGenerate > {
  static const char* value()
  {
    return "82bcd62a338b6421f3f91564dfc93990";
  }

  static const char* value(const ::emotion_server::EmotionGenerate&) { return value(); }
};

template<>
struct DataType< ::emotion_server::EmotionGenerate > {
  static const char* value()
  {
    return "emotion_server/EmotionGenerate";
  }

  static const char* value(const ::emotion_server::EmotionGenerate&) { return value(); }
};


// service_traits::MD5Sum< ::emotion_server::EmotionGenerateRequest> should match
// service_traits::MD5Sum< ::emotion_server::EmotionGenerate >
template<>
struct MD5Sum< ::emotion_server::EmotionGenerateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::emotion_server::EmotionGenerate >::value();
  }
  static const char* value(const ::emotion_server::EmotionGenerateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::emotion_server::EmotionGenerateRequest> should match
// service_traits::DataType< ::emotion_server::EmotionGenerate >
template<>
struct DataType< ::emotion_server::EmotionGenerateRequest>
{
  static const char* value()
  {
    return DataType< ::emotion_server::EmotionGenerate >::value();
  }
  static const char* value(const ::emotion_server::EmotionGenerateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::emotion_server::EmotionGenerateResponse> should match
// service_traits::MD5Sum< ::emotion_server::EmotionGenerate >
template<>
struct MD5Sum< ::emotion_server::EmotionGenerateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::emotion_server::EmotionGenerate >::value();
  }
  static const char* value(const ::emotion_server::EmotionGenerateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::emotion_server::EmotionGenerateResponse> should match
// service_traits::DataType< ::emotion_server::EmotionGenerate >
template<>
struct DataType< ::emotion_server::EmotionGenerateResponse>
{
  static const char* value()
  {
    return DataType< ::emotion_server::EmotionGenerate >::value();
  }
  static const char* value(const ::emotion_server::EmotionGenerateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EMOTION_SERVER_MESSAGE_EMOTIONGENERATE_H
