// Generated by gencpp from file pal_web_msgs/GetLastTouchWeb.msg
// DO NOT EDIT!


#ifndef PAL_WEB_MSGS_MESSAGE_GETLASTTOUCHWEB_H
#define PAL_WEB_MSGS_MESSAGE_GETLASTTOUCHWEB_H

#include <ros/service_traits.h>


#include <pal_web_msgs/GetLastTouchWebRequest.h>
#include <pal_web_msgs/GetLastTouchWebResponse.h>


namespace pal_web_msgs
{

struct GetLastTouchWeb
{

typedef GetLastTouchWebRequest Request;
typedef GetLastTouchWebResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLastTouchWeb
} // namespace pal_web_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pal_web_msgs::GetLastTouchWeb > {
  static const char* value()
  {
    return "f9395367802b9132f5764b023404f09b";
  }

  static const char* value(const ::pal_web_msgs::GetLastTouchWeb&) { return value(); }
};

template<>
struct DataType< ::pal_web_msgs::GetLastTouchWeb > {
  static const char* value()
  {
    return "pal_web_msgs/GetLastTouchWeb";
  }

  static const char* value(const ::pal_web_msgs::GetLastTouchWeb&) { return value(); }
};


// service_traits::MD5Sum< ::pal_web_msgs::GetLastTouchWebRequest> should match
// service_traits::MD5Sum< ::pal_web_msgs::GetLastTouchWeb >
template<>
struct MD5Sum< ::pal_web_msgs::GetLastTouchWebRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pal_web_msgs::GetLastTouchWeb >::value();
  }
  static const char* value(const ::pal_web_msgs::GetLastTouchWebRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_web_msgs::GetLastTouchWebRequest> should match
// service_traits::DataType< ::pal_web_msgs::GetLastTouchWeb >
template<>
struct DataType< ::pal_web_msgs::GetLastTouchWebRequest>
{
  static const char* value()
  {
    return DataType< ::pal_web_msgs::GetLastTouchWeb >::value();
  }
  static const char* value(const ::pal_web_msgs::GetLastTouchWebRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pal_web_msgs::GetLastTouchWebResponse> should match
// service_traits::MD5Sum< ::pal_web_msgs::GetLastTouchWeb >
template<>
struct MD5Sum< ::pal_web_msgs::GetLastTouchWebResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pal_web_msgs::GetLastTouchWeb >::value();
  }
  static const char* value(const ::pal_web_msgs::GetLastTouchWebResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_web_msgs::GetLastTouchWebResponse> should match
// service_traits::DataType< ::pal_web_msgs::GetLastTouchWeb >
template<>
struct DataType< ::pal_web_msgs::GetLastTouchWebResponse>
{
  static const char* value()
  {
    return DataType< ::pal_web_msgs::GetLastTouchWeb >::value();
  }
  static const char* value(const ::pal_web_msgs::GetLastTouchWebResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAL_WEB_MSGS_MESSAGE_GETLASTTOUCHWEB_H
